---
title: "Autoencoder"
author: "Spencer Ferguson-Dryden"
date: "5/9/2021"
output: pdf_document
---
```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, error = FALSE)
```

```{r echo = TRUE, eval = TRUE, include = FALSE}
# Load libraries
library(tidyverse)
library(here)
library(amerika)
library(tictoc)
library(h2o) # ML engine for fitting the AE
library(bit64) # speeds up some h2o computation
```

Cleaning/Recoding

```{r}
anes <- readRDS("clean.rds")

# Collapse Party/Ideology into broader groups
anes <- anes %>% mutate(
  ideology = fct_collapse(
  ideology,
  Liberal=c("Extremely Liberal", "Liberal", "Slightly Liberal"),
  Conservative=c("Extremely Conservative", "Conservative", "Slightly Conservative"))) %>%
  mutate(
  party=fct_collapse(
  party,
  Democrat=c("Strong Democrat", "Democrat", "Lean Democrat"),
  Republican=c("Strong Republican", "Republican", "Lean Republican")))

# Isolate response/predictors by predictor type (otherwise too few items in dataset)
radio <- anes %>%
  dplyr::select(starts_with(c("radio_", "ft_", "party", "ideology", "race", "gender"))) %>%
  na.omit()
tv_news <- anes %>%
  dplyr::select(starts_with(c("ft_", "party", "ideology", "race", "gender", "tv_all_in_with_chris_hayes", "tv_hannity", "tv_60_minutes", "tv_anderson_cooper", "tv_cbs", "tv_face_the_nation", "tv_nbc", "tv_the_rachel", "tv_pbs", "tv_the_o_reilly"))) %>%
  na.omit()
tv_series <- anes %>% 
  dplyr::select(starts_with(c("ft_", "party", "ideology", "race", "gender", "tv_criminal", "tv_empire", "tv_modern_family", "tv_ncis", "tv_the_simpsons", "tv_house_of_cards", "tv_game_of_thrones", "tv_blue_bloods", "tv_hawaii", "tv_madam_sec", "tv_scandal", "tv_the_big_bang"))) %>%
  na.omit()
tv_game_talk_shows <- anes %>%
  dplyr::select(starts_with(c("ft_", "party", "ideology", "race", "gender", "tv_good_morning", "tv_today", "tv_jimmy", "tv_dancing", "tv_judge", "tv_shark_tank", "tv_the_voice", "tv_the_late_show", "tv_the_tonight_show"))) %>%
  na.omit()
web <- anes %>%
  dplyr::select(starts_with(c("web_", "ft_", "party", "ideology", "race", "gender"))) %>%
  na.omit()
```

Constructing the Autoencoder

```{r results='hide', message=FALSE}

set.seed(1234)
my_h2o <- h2o.init()

# CHANGE VARIABLE NAME HERE
anes_h2o <- tv_news %>% as.h2o() 


split_frame <- h2o.splitFrame(anes_h2o, 
                              ratios = c(0.8, 0.1), 
                              seed = 1234)   
split_frame %>% 
  str()
train <- split_frame[[1]]
validation <- split_frame[[2]]
test <- split_frame[[3]]

# Select response/predictor variables
response <- tv_news %>% # CHANGE VARIABLE HERE
  dplyr::select(starts_with(c("tv_"))) %>% names() # CHANGE SELECTOR VALUE
response <- append(response, 
                   c('ideology', 'party', 'race', 'gender')
                   )
predictors <- setdiff(colnames(train), response)
```


```{r results='hide'}
# Run the AE algorithm with 1 layer and 2 nodes
tic()
autoencoder <- h2o.deeplearning(x = predictors,
                                training_frame = train,
                                autoencoder = TRUE,  
                                hidden = c(8, 8, 2),
                                epochs = 1000, 
                                activation = "Tanh")
toc()
```

For reference, get the index and colnames of the training dataset
```{r}
names(train)
```

```{r}
codings_train <- h2o.deepfeatures(autoencoder, 
                                  data = train, 
                                  layer = 3) %>%
  as.data.frame() %>%
  # CHANGE/ADD FEATURES HERE
  mutate(response = as.vector(train[ , 45])) %>%
  mutate(ideology = as.vector(train[ , 33]))

ggplot(codings_train, aes(x = DF.L3.C1, 
                          y = DF.L3.C2, 
                          color = factor(response),
                          shape = factor(ideology))) +
  geom_point(alpha = 0.8) + 
  stat_ellipse(aes(group=factor(response))) +
  # CHANGE LABELS AS NEEDED
  labs(title = "Deep Features (Three Layers)",
       color = "O'Reilly Factor",
       shape = "Ideology") + 
  theme_minimal()
```


```{r}
# viz relative importance
fimp <- as.data.frame(h2o.varimp(autoencoder)) %>% 
  arrange(desc(relative_importance))

fimp %>% 
  ggplot(aes(x = relative_importance, 
             y = reorder(variable, -relative_importance))) +
  geom_point(color = "dark red", 
             fill = "dark red", 
             alpha = 0.5,
             size = 2) +
  labs(title = "Relative Feature Importance",
       subtitle = "Deep Autoencoder",
       x = "Relative Importance",
       y = "Feature") + 
  theme_minimal()
```

