---
title: "Data"
author: "Rubén A. Rodríguez Barrón"
date: "4/26/2021"
output: pdf_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE, error = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(readstata13)
library(skimr)
library(psych)
```

# Data

This is the file where we will clean the data from **anes_timeseries_2016_Stata13.dta**. The raw data can be accessed [here](https://electionstudies.org/data-center/2016-time-series-study/).

The data frame *clean.rds* should be used in all working files of the project. 

```{r}
raw <- read.dta13("anes_timeseries_2016_Stata13.dta")
```

```{r}
clean <- raw %>% 
  #Please add your lines in ANES order
  select(ideology = V161126,
         party = V161158x,
         race = V161310x,
         gender = V161342,
         radio_rush_limbaugh = V161428,
         radio_morning_edition = V161429,
         radio_the_sean_hannity_show = V161430,
         radio_all_things_considered	=	V161431,
         radio_marketplace	=	V161432,
         radio_the_glenn_beck_program	=	V161433,
         radio_the_mark_levin_show	=	V161434,
         radio_the_savage_nation	=	V161435,
         radio_fresh_air	=	V161436,
         radio_the_hugh_hewitt_show	=	V161437,
         radio_the_thom_hartmann_program	=	V161438,
         radio_joe_madison	=	V161439,
         radio_the_mike_gallagher_show	=	V161440,
         radio_the_bill_handel_show	=	V161441,
         radio_the_schnitt_show	=	V161442,
         radio_no_radio	=	V161443,
         tv_20_20 = V161364,
         tv_all_in_with_chris_hayes = V161365,
         tv_the_blacklist = V161366,
         tv_evening_news_with_scott = V161367,
         tv_criminal_minds = V161368,
         tv_empire = V161369,
         tv_hannity = V161370,
         tv_jimmy_kimmel_live = V161371,
         tv_the_kelly_file = V161372,
         tv_modern_family = V161373,
         tv_ncis = V161374,
         tv_the_nightly_show_with_larry = V161375,
         tv_sunday_night_football = V161376,
         tv_scorpion = V161377,
         tv_the_simpsons = V161378,
         tv_today = V161379,
         tv_60_minutes = V161380,
         tv_anderson_cooper_360 = V161381,
         tv_cbs_this_morning = V161382,
         tv_dancing_with_the_stars = V161383,
         tv_face_the_nation = V161384,
         tv_house_of_cards = V161385,
         tv_hardball_with_chris_matthews = V161386,
         tv_judge_judy = V161387,
         tv_meet_the_press = V161388,
         tv_game_of_thrones = V161389,
         tv_nbc_nightly_news_with_lester_holt = V161390,
         tv_on_the_record_with_greta_van_susteren = V161391,
         tv_daredevil = V161392,
         tv_the_rachel_maddow_show = V161393,
         tv_shark_tank = V161394,
         tv_the_voice = V161395,
         tv_abc_world_news_with_david_muir = V161396,
         tv_blue_bloods = V161397,
         tv_conan = V161398,
         tv_dateline_nbc = V161399,
         tv_good_morning_america = V161400,
         tv_hawaii_five_o = V161401,
         tv_madam_secretary = V161402,
         tv_nancy_grace = V161403,
         tv_erin_burnett_outfront = V161404,
         tv_pbs_news_hour = V161405,
         tv_scandal = V161406,
         tv_the_big_bang_theory = V161407,
         tv_the_late_show_with_stephen_colbert = V161408,
         tv_the_o_reilly_factor = V161409,
         tv_the_tonight_show_starring_jimmy_fallon = V161410,
         tv_alpha_house = V161411,
         tv_al_punto = V161412,
         tv_al_rojo_vivo = V161413,
         tv_aqui_y_ahora = V161414,
         tv_cnn_en_espanol = V161415,
         tv_despierta_america = V161416,
         tv_el_gordo_y_la_flaca = V161417,
         tv_enfoque = V161418,
         tv_hoy = V161419,
         tv_lo_mejor_de_caso_cerrado = V161420,
         tv_noticiero_enrique_gratas = V161421,
         tv_noticiero_telemundo = V161422,
         tv_noticiero_univision = V161423,
         tv_el_senor_de_los_cielos = V161424,
         tv_que_noche_con_angelica_y_raul = V161425,
         tv_primer_impacto = V161426,
         tv_cronicas_de_sabado = V161427,
         ft_obama	=	V161092,
         ft_bill_clinton	=	V161093,
         ft_democratic_party	=	V161095,
         ft_republican_party	=	V161096,
         ft_clinton	=	V162078,
         ft_trump	=	V162079,
         ft_johnson	=	V162080,
         ft_stein	=	V162081,
         ft_kaine	=	V162091,
         ft_pence	=	V162092,
         ft_john_roberts	=	V162093,
         ft_pope_francis	=	V162094,
         ft_christian_fundamentalists = V162095,
         ft_feminists = V162096,
         ft_liberals = V162097,
         ft_labor_unions = V162098,
         ft_poor_people = V162099,
         ft_big_business = V162100,
         ft_conservatives = V162101,
         ft_supreme_court = V162102,
         ft_gay_lesbian = V162103,
         ft_congress = V162104,
         ft_rich_people = V162105,
         ft_muslims = V162106,
         ft_christians = V162107,
         ft_jews = V162108,
         ft_tea_party = V162109,
         ft_police= V162110,
         ft_transgender_people = V162111,
         ft_scientists = V162112,
         ft_blm = V162113) %>% 
  
  # Recoding ideology
  mutate(ideology = dplyr::recode(ideology,
                        `-9` = NA_real_,
                        `-8` = NA_real_,
                        `99` = NA_real_)) %>% 
  # Recoding party
  mutate(party = dplyr::recode(party,
                        `-9` = NA_real_,
                        `-8` = NA_real_)) %>% 
  # Recoding race
  mutate(race = dplyr::recode(race,
                        `-9` = NA_real_)) %>% 
  # Recoding gender
  mutate(gender = dplyr::recode(gender,
                        `-9` = NA_real_,
                        `3`  = NA_real_)) %>% 
  # Recoding tv
  mutate_at(vars(contains("tv_")), funs(if_else(.<0,NA_real_,.))) %>% 
  # Recoding radio
  mutate_at(vars(contains("radio_")), funs(if_else(.<0,NA_real_,.))) %>% 
  # Recoding web
  mutate_at(vars(contains("web_")), funs(if_else(.<0,NA_real_,.))) %>%
  # Recoding thermometers
  mutate_at(vars(contains("ft_")), funs(if_else(.<0 | .>100, NA_real_,.)))
```

```{r}
# Set factors for ideology
clean$ideology <- factor(clean$ideology, labels=c("Extremely Liberal", "Liberal", "Slightly Liberal", "Moderate", "Slightly Conservative", "Conservative", "Extremely Conservative"))

# Set factors for party
clean$party <- factor(clean$party, labels=c("Strong Democrat", "Democrat", "Lean Democrat", "Independent", "Lean Republican", "Republican", "Strong Republican"))
```

```{r}
# Save a single object to a file
saveRDS(clean, "clean.rds")
```

